### ISSUE TITLE
master is broken for yarn start local usage

### ISSUE THREAD

**Issue by Arrowana** [project-serum/sol-wallet-adapter#19]
It seems like the following PR #15
Completely broke local development, or even more.

I did `cd example && yarn install && yarn start`

I get errors all over the place
![image](https://user-images.githubusercontent.com/8245419/109941119-edfde200-7d26-11eb-8e0e-1527ef8b5f44.png)

I checked out commit 63a823ff699f9df686fb78d1a041d67a6889ca8a then `yarn start` leads to a functional page again.

**Comment by usmane3** [comment]
Same problem
